<a href="https://colab.research.google.com/github/Pavel184/PyTorch_basic_course/blob/Homework_lesson_1/Homework_lesson_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
# Создайте случайный FloatTensor размера 3x4x5
x = torch.arange(60).view(3,4,5)
x

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]],

        [[40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49],
         [50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59]]])

In [3]:
y = torch.DoubleTensor(3, 4, 5) # 64-bit float
y

tensor([[[4.6597e-310,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]]],
       dtype=torch.float64)

In [4]:
# Выведите его форму (shape)
x.shape

torch.Size([3, 4, 5])

In [5]:
# Приведите его к форме 6 X 10
x = x.view(6,10)
x.shape

torch.Size([6, 10])

In [6]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно
x.view(12,5) * torch.LongTensor([1, 4, 2, 2, 1]) 

tensor([[  0,   4,   4,   6,   4],
        [  5,  24,  14,  16,   9],
        [ 10,  44,  24,  26,  14],
        [ 15,  64,  34,  36,  19],
        [ 20,  84,  44,  46,  24],
        [ 25, 104,  54,  56,  29],
        [ 30, 124,  64,  66,  34],
        [ 35, 144,  74,  76,  39],
        [ 40, 164,  84,  86,  44],
        [ 45, 184,  94,  96,  49],
        [ 50, 204, 104, 106,  54],
        [ 55, 224, 114, 116,  59]])

In [7]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
torch.matmul(x, torch.transpose(x, 0, 1)).shape

torch.Size([6, 6])

In [8]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
#y' = 3*x**2 (3, 0.75, 12)

In [105]:
from torch.autograd import grad, Variable
x = Variable(torch.HalfTensor([1, 0.5, 2]), requires_grad=True)
x

tensor([1.0000, 0.5000, 2.0000], dtype=torch.float16, requires_grad=True)

In [106]:
y = torch.sum(x**3)
y

tensor(9.1250, dtype=torch.float16, grad_fn=<SumBackward0>)

In [108]:
y.backward()

In [109]:
x.grad

tensor([ 3.0000,  0.7500, 12.0000], dtype=torch.float16)

In [83]:
# Создайте единичный тензор размера 5x6
x = torch.ones([5,6])
x

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [15]:
# Переведите его в формат numpy
x = x.numpy()
x

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)

In [16]:
# Давайте теперь пооптимизируем: возьмите функцию y = x**w1 - 2 * x**2 + 5
# Посчитайте 
from torch import nn 
from torch import optim


In [17]:
# Задаём функцию потерь
criterion = nn.MSELoss()

In [51]:
# Задаём переменные
x = Variable(torch.randn(1), requires_grad = True)
b = Variable(torch.Tensor([5]), requires_grad = True)
w_1 = Variable(torch.randn(1), requires_grad = True)
y = Variable(torch.randn(1), requires_grad = False)

In [52]:
# инициализируем оптимизатор
optimizer = torch.optim.SGD((w_1, b), lr=0.01)

In [53]:
print("x ", x)
print("y ", y)

x  tensor([0.2160], requires_grad=True)
y  tensor([1.0814])


In [54]:
print("w ", w_1)
print("b ", b)

w  tensor([0.8861], requires_grad=True)
b  tensor([5.], requires_grad=True)


In [55]:
print ('dL/dw: ', w_1.grad) 
print ('dL/db: ', b.grad)

dL/dw:  None
dL/db:  None


In [56]:
# Обнуляем градиенты и делаем прямой проход
optimizer.zero_grad()
pred = x**w_1 - 2 * x**2 + b
loss = criterion(pred, y)
print('loss: ', loss.item())


loss:  16.666105270385742


In [57]:
loss.backward()

In [58]:
print ('dL/dw: ', w_1.grad) 
print ('dL/db: ', b.grad)

dL/dw:  tensor([-3.2178])
dL/db:  tensor([8.1648])


In [59]:
optimizer.step()

In [60]:
print("w ", w_1)
print("b ", b)

w  tensor([0.9183], requires_grad=True)
b  tensor([4.9184], requires_grad=True)
